### ISSUE TITLE
Doesn't sync changed files

### ISSUE THREAD

**Issue by nsrosenqvist** [mrmlnc/syncy#34]
Syncy only syncs files that are either new or have been removed, not changed. Which removes a whole heap of use cases for this.

**Comment by mrmlnc** [comment]
Hello, @nsrosenqvist,

Most likely your editor or any other software does not update file modification time. You use Syncy with remote disk or other softare for sync files? Also, can you provide steps by which I could reproduce your issue?

**Comment by mrmlnc** [comment]
Closed, because we have no feedback.

**Comment by tommcc** [comment]
I am having the same issue, and I believe it's because syncy is using creation time instead of modification time in its [update check](https://github.com/mrmlnc/syncy/blob/ddfde44d0d5943e000f8df90fb090b9a99fed9d3/src/syncy.ts#L41).

A file that was previously copied, but has now been altered will still have the same `ctime`, but a newer `mtime`.

**Comment by tommcc** [comment]
Actually, another part of the problem is that the `updateAndDelete` flag is doing more than advertised. No updating of existing files occurs if this is not set to true, while the documentation implies that this will only affect deletions.
